run:
  deadline: 5m

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

  # We want to try and improve the comments in the k6 codebase, so individual
  # non-golint items from the default exclusion list will gradually be addded
  # to the exclude-rules below
  exclude-use-default: false

linters-settings:
  govet:
    check-shadowing: true
  cyclop:
    max-complexity: 25
  maligned:
    suggest-new: true
  dupl:
    threshold: 150
  goconst:
    min-len: 10
    min-occurrences: 4
  funlen:
    lines: 80
    statements: 60

linters:
  enable-all: true
  disable:
  - exhaustivestruct
  - forbidigo
  - gci
  - gochecknoinits
  - gocyclo # replaced by cyclop since it also calculates the package complexity
  - godot
  - godox
  - goerr113 # most of the errors here are meant for humans
  - goheader
  - golint # deprecated
  - gomnd
  - gomodguard
  - interfacer # deprecated
  - ireturn
  - lll
  - maligned # replaced by govet 'fieldalignment'
  - nlreturn
  - scopelint # deprecated, replaced by exportloopref
  - tagliatelle
  - testpackage
  - thelper
  - varnamelen
  - wrapcheck
  - wsl
  fast: false
